---
repos:
  # Check commit messages on commit
  - repo: https://github.com/commitizen-tools/commitizen
    # Specify tag
    rev: v2.17.13
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/python/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
