---
repos:
  # Check commit messages on commit
  - repo: https://github.com/commitizen-tools/commitizen
    # Specify tag
    rev: v2.29.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
      - id: black-jupyter
        language_version: python3
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.5
    hooks:
      - id: blackdoc
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        # Skip test_template!!
        files: "^\\w+\\.py$"
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        files: ^test_template/
