# Changes here will be overwritten by Copier
_src_path: https://github.com/nialov/nialov-py-template.git
description: Python package for stuff.
email: nikolasovaskainen@gmail.com
full_name: Nikolas Ovaskainen
github_account: nialov
package: mypackage
year: 2021
classifier: "Topic :: Scientific/Engineering :: GIS"
keyword: data
