name: Test template

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "41 7 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "action"
      - name: Cache /nix
        uses: actions/cache@v2
        with:
          path: /nix/store
          key: ${{ runner.os }}-${{ hashFiles('flake.lock') }}-nix-store
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Cache .nox
        uses: actions/cache@v2
        with:
          path: .nox
          key: ${{ runner.os }}-${{ hashFiles('noxfile.py') }}-${{ hashFiles('flake.lock') }}-nox
      - name: Nox installs depencies including pipx which launches nox
        run: |
          nix -Lv develop -c pipx run nox --version
          nix -Lv develop -c pipx run nox
