name: Test template

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "41 7 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "action"
        # Both caching /nix/store and .nox are probably inefficient
        # nix cache pulls from cache.nixos.org are already fast
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nialov
          # If you chose signing key for write access
          # signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a
          # private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Cache .nox
        uses: actions/cache@v3
        with:
          path: .nox
          key: ${{ runner.os }}-${{ hashFiles('noxfile.py') }}-${{ hashFiles('flake.lock') }}-nox
      - name: Check flake
        run: |
          nix -Lv flake check
      - name: Poetry installs python dependencies, including nox
        run: |
          nix -Lv develop -c poetry install
          nix -Lv develop -c poetry run nox
