name: Test template

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "41 7 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "action"
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Nox installs depencies including pipx which launches nox
        run: |
          nix -Lv develop -c pipx run nox
