on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v2
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v12
        with:
          name: nialov
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check flake
        run: |
          nix flake check
      - name: Run copier template tests
        run: |
          nix run .#template-test
